### ISSUE TITLE
Event recognition

### ISSUE THREAD

**Issue by Janmm14** [Photon-GitHub/AACAddition#2]
https://github.com/Photon-GitHub/AACAddition/blob/master/src/main/java/de/photon/aacaddition/modules/fixes/FastbreakFix.java#L34

I'd use nms reflection to get the current tick number and check if both events are in the same tick. And each time after you cancelled a violation, invalidate the bypass.

And if user breaks another block invalidate the bypass too.

1 second without fastbreak check is too much.

You can use similar techniques with other bypasses in all proper synced aac checks (movement not sync prior to 3.6.4)

**Comment by Photon-GitHub** [comment]
The problem is that the Fastbreak violation is not that the block itself was broken too fast, but that the interaction with the next block was done too fast. Therefore I cannot use your proposed method.
I will make the fastbreak delay configurable. Also I doubt that many people use this to bypass AAC for one second, after all you need to break cocoa and have an axe in hand.

**Comment by Janmm14** [comment]
Ahh, okay
